wandb_version: 1

depth:
  desc: null
  value: 3
lr:
  desc: null
  value: 6.85185936451438e-05
epochs:
  desc: null
  value: 40000
batch_size:
  desc: null
  value: 52
hidden_dim:
  desc: null
  value: 23
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688239973.855405
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      2:
      - 1
      - 41
      - 51
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.11
      5: 0.15.3
      8:
      - 5
